### ISSUE TITLE
Internal Server Error when running on Visual Studio Code

### ISSUE THREAD

**Issue by worldeditor11** [DangerOnTheRanger/maniwani#68]
Downloaded the whole thing, followed the instructions on running it without docker but upon navigating to http://127.0.0.1:5000, multiple errors pop up on the console. The page itself only displays 500 Internal Server Error.

Error on console:
`
pipenv run flask run
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-03-26 09:00:09,535] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\Maniwani\blueprints\main.py", line 13, in index
    return render_template("index.html", greeting=greeting, threads=Firehose().get_impl())
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Projects\Maniwani\templates\index.html", line 1, in top-level template code
    {%- extends "base.html" %}
  File "C:\Projects\Maniwani\templates\base.html", line 16, in top-level template code
    <title>{{ instance_name() }} - {% block title %}{% endblock %}</title>
  File "C:\Projects\Maniwani\app.py", line 57, in instance_name
    return app.config["INSTANCE_NAME"]
KeyError: 'INSTANCE_NAME'
[2019-03-26 09:00:09,538] ERROR in app: Traceback (most recent call last):
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\Maniwani\blueprints\main.py", line 13, in index
    return render_template("index.html", greeting=greeting, threads=Firehose().get_impl())
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Projects\Maniwani\templates\index.html", line 1, in top-level template code
    {%- extends "base.html" %}
  File "C:\Projects\Maniwani\templates\base.html", line 16, in top-level template code
    <title>{{ instance_name() }} - {% block title %}{% endblock %}</title>
  File "C:\Projects\Maniwani\app.py", line 57, in instance_name
    return app.config["INSTANCE_NAME"]
KeyError: 'INSTANCE_NAME'

127.0.0.1 - - [26/Mar/2019 09:00:09] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "C:\Projects\Maniwani\app.py", line 51, in internal_server_error
    return render_template("internal-error.html"), 500
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Projects\Maniwani\templates\internal-error.html", line 1, in top-level template code
    {%- extends "base.html" %}
  File "C:\Projects\Maniwani\templates\base.html", line 16, in top-level template code
    <title>{{ instance_name() }} - {% block title %}{% endblock %}</title>
  File "C:\Projects\Maniwani\app.py", line 57, in instance_name
    return app.config["INSTANCE_NAME"]
KeyError: 'INSTANCE_NAME'
`

**Comment by DangerOnTheRanger** [comment]
I think it can't find a configuration file; try setting the environment variable `MANIWANI_CFG` to `./deploy-configs/devmode.cfg` before running `pipenv run flask run`. If that's the case, I'll update the README accordingly.
The non-Docker installation/setup path is probably lagging behind a little bit documentation-wise since I don't actively use it as much, so I appreciate you submitting this issue and helping to bring it back up to speed.

**Comment by worldeditor11** [comment]
Created a .env file with only the following line:
`MANIWANI_CFG=./deploy-configs/devmode.cfg`

When I run `'pipenv run flask run`, now it returns:

pipenv run flask run
Loading .env environment variables…
Traceback (most recent call last):
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\cli\command.py", line 408, in run
    command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 2317, in do_run
    load_dot_env()
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 172, in load_dot_env
    dotenv.load_dotenv(dotenv_file, override=True)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\dotenv\main.py", line 262, in load_dotenv
    return DotEnv(f, verbose=verbose).set_as_environment_variables(override=override)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\dotenv\main.py", line 105, in set_as_environment_variables
    os.environ[k] = v
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\os.py", line 684, in __setitem__
    self.putenv(key, value)
ValueError: embedded null character

**Comment by DangerOnTheRanger** [comment]
I have no idea how it would have ended up in there, but that's saying there's a NULL\`\0` embedded in there somewhere. Try deleting and re-typing out the value by hand if you copied it, and if the file doesn't end in a blank new line, add one. If there's no new line, it may be treating the file-terminating `\0` as a part of the environment variable's value, ending up with the error it gave.

**Comment by worldeditor11** [comment]
Yeah, figured that's the case so I did exactly that. For VSCode users like myself, if you tried to create a .env file using the echo command, it will give you this embedded null character error. To fix this, go to your project folder (with app.py etc.), create new text document, copy and paste `MANIWANI_CFG=./deploy-configs/devmode.cfg` into your text file, save it as `.env`, change the `Save as type` to `All Files (*)` and finally hit the save button.

However, another internal server error pops up but this time the site actually rendered its content.

![image](https://user-images.githubusercontent.com/25149172/54978846-59ff3980-4f99-11e9-962f-de576fdaecc6.png)

**Comment by DangerOnTheRanger** [comment]
Did anything pop up on the command line when the error occurred? CSS/JS are obviously getting sent over, so I'm suspecting the database didn't bootstrap properly (you might have to run `pipenv run python bootstrap.py` again).

**Comment by worldeditor11** [comment]
Yup apparently the last time I run it was without the .env file. So that pretty much fixes it.

Have to create a bunch of new threads but at least now I can play it around a bit. (Missing the mascot?)
![image](https://user-images.githubusercontent.com/25149172/54980695-54582280-4f9e-11e9-9b44-c31bc3bb9286.png)

**Comment by DangerOnTheRanger** [comment]
There's a file called `index-greeting.html` in the `deploy-configs` directory that controls the little banner that gets displayed above the threads; Futatsu's is changed to display the mascot:
```
<div class="p-5">
	<div class="row">
		<div class="col-md-6 col-lg-5">
			<img class="img-fluid" src="https://cdn.futatsu.org/mascot.png">
		</div>
		<div class="w-100 d-block d-lg-none"></div>
		<div class="col-auto col-lg-6">
			<p class="display-4">The maker's haven.</p>
			<hr class="my-4">
			<p>Futatsu is an imageboard intended to promote and discuss all different kinds of self-made digital content! Come
				and discuss best practices for programming, drawing, and more, get feedback on your
				work-in-progress, or show off your latest creation. Below, you can find the most
				recently-updated threads on the site.</p>
		</div>
	</div>
</div>
```

It's just a snippet of HTML that gets injected into the body of the front page, so it's super easy to change if you want to change it.
You don't have an S3 store or anything like that running, do you? I ask since I thought #36 was still at-large (though I haven't worked on it in a while), but if you have `MANIWANI_CFG=./deploy-configs/devmode.cfg` and didn't modify the config file you're using the file-and-folder storage backend that I thought was broken (but apparently it's not), so that's a pleasant surprise.

**Comment by worldeditor11** [comment]
Nope, no idea what S3 storage is. So, no, most likely not. Though theres a strange behaviour whenever I created a new thread it will return an internal server error. Upon refreshing or just navigating back to the board, the new thread is in the catalog. Similar case when posting a reply as well. Strange stuff.

And yeah, commented out the old banner and replaced it with your code. Working as intended.

![image](https://user-images.githubusercontent.com/25149172/54984022-ddbf2300-4fa5-11e9-9eee-705d481ff6db.png)

**Comment by DangerOnTheRanger** [comment]
If it's returning HTTP 500s at you, there should be some info visible on the command line - is anything printed there? If the catalog and threads are rendering fine, it's probably something to do with the redirect immediately after creating a new thread/post, though I don't know why that would be causing an error, either.

**Comment by worldeditor11** [comment]
Repeated the whole flow for better clarity.

pipenv run flask run
Loading .env environment variables…
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Mar/2019 17:20:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 17:20:06] "GET /upload/thumb/4 HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 17:20:20] "GET /threads/4 HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 17:20:21] "GET /upload/4 HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 17:20:31] "GET /boards/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 17:20:32] "GET /boards/1 HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 17:20:33] "GET /threads/new/1 HTTP/1.1" 200 -
[2019-03-26 17:20:59,955] ERROR in app: Exception on /threads/new [POST]
Traceback (most recent call last):
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\Maniwani\blueprints\threads.py", line 40, in submit
    thread = NewThread().post_impl()
  File "C:\Projects\Maniwani\model\NewThread.py", line 47, in post_impl
    NewPost().post(thread_id=thread.id)
  File "C:\Projects\Maniwani\model\NewPost.py", line 120, in post
    pubsub_client = keystore.Pubsub()
  File "C:\Projects\Maniwani\keystore.py", line 48, in __init__
    self._client.connect()
  File "C:\Projects\Maniwani\storestub.py", line 178, in connect
    self._socket.connect(("127.0.0.1", PUBSUB_PORT))
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\gevent\_socket3.py", line 335, in connect
    raise error(err, strerror(err))
ConnectionRefusedError: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.
[2019-03-26 17:20:59,959] ERROR in app: Traceback (most recent call last):
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\Maniwani\blueprints\threads.py", line 40, in submit
    thread = NewThread().post_impl()
  File "C:\Projects\Maniwani\model\NewThread.py", line 47, in post_impl
    NewPost().post(thread_id=thread.id)
  File "C:\Projects\Maniwani\model\NewPost.py", line 120, in post
    pubsub_client = keystore.Pubsub()
  File "C:\Projects\Maniwani\keystore.py", line 48, in __init__
    self._client.connect()
  File "C:\Projects\Maniwani\storestub.py", line 178, in connect
    self._socket.connect(("127.0.0.1", PUBSUB_PORT))
  File "c:\users\me\.virtualenvs\maniwani-2ggrbk5h\lib\site-packages\gevent\_socket3.py", line 335, in connect
    raise error(err, strerror(err))
ConnectionRefusedError: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.

127.0.0.1 - - [26/Mar/2019 17:20:59] "POST /threads/new HTTP/1.1" 500 -

**Comment by DangerOnTheRanger** [comment]
Basically, Maniwani tries to use either Redis or it's own [stub key-value/pubsub store](https://github.com/DangerOnTheRanger/maniwani/blob/master/storestub.py) as a backend for when users/clients need to be notified via push updates of threads being made, posts being added/replied to, etc. `devmode.cfg` by default assumes the stub key-value store will be used, so Maniwani attempts to make a connection to it, but it's not running since I forgot to put a note to start it up into the documentation for the non-Docker setup route, whoops.

You can safely ignore the error unless you want to play with the live update functionality, but if you want to get rid of it, just run `pipenv run python storestub.py` and that should fix things by starting up the stub key-value server. You'll probably want a separate command line window for that since `storestub.py` will run in the foreground and you won't get back to the command prompt.

**Comment by worldeditor11** [comment]
You sir, are awesome. Need to create another instance of cmd but everything works.

**Comment by DangerOnTheRanger** [comment]
Glad to hear it everything's running smoothly - I'll close this issue for now since it seems everything is in order, but feel free to comment again or make another one if a problem arises.
